### PR TITLE
Fixed Some Bugs

### PR DESCRIPTION
**Pull request by coke11**
I might have just made it worse. It still needs to be tested. That is why this is a PR.

### CODE REVIEW

**Comment by coke11** [comment]
[Logos, Proffesional :D](https://trello.com/c/P4kLVcwQ/226-logos-proffesional-d)

**Comment by coke11** [comment]
@NaturalmotionStudios Yeah. I am afraid there might still be some more bugs though...

**Comment by NaturalmotionStudios** [comment]
@coke11 Well right now the preview button isn't working...

**Comment by coke11** [comment]
@NaturalmotionStudios Nothing is working now...

**Comment by NaturalmotionStudios** [comment]
@coke11 Fixing it right now...

**Comment by NaturalmotionStudios** [comment]
@coke11 
capture

**Pull request merged**
